### PR TITLE
Doc: README.md - Include BlueBanquise

### PR DESCRIPTION
**Pull request by oxedions**
Dear maintainers,

This is a proposal to include BlueBanquise project resources into your awesome list 😊

### CODE REVIEW

**Comment by IronTooch** [comment]
@oxedions, if you want to submit a pull request at https://github.com/IronTooch/awesome-ansible, I'm happy to include and start maintaining. Looks like this repo needs to be archived.

**Comment by IronTooch** [comment]
@oxedions  Opened an issue to see if this is still being maintained, but if not, happy to accept a Pull Req at https://github.com/IronTooch/awesome-ansible

**Comment by oxedions** [comment]
Dear @IronTooch 

Tanks a lot. Lets see if your issue obtains an answer. If not, yes I would be glad BaluBanquise to be added to your fork 😊

**Comment by KeyboardInterrupt** [comment]
Hi, I checked out BlueBanquise, I would like to add it to the List, though may I ask you to fix the problem pointed out by the Linter:
https://github.com/KeyboardInterrupt/awesome-ansible/runs/5751700726?check_suite_focus=true
```
  README.md:115:68
  ✖  115:68  List item link and description must be separated with a dash  remark-lint:awesome-list-item

  1 error
```
Also, please, either add the Community Link as an individual item, or omit it, and only add the CORE Portion of BlueBanquiese.

---

_On a personal side Note, I have seen that Ubuntu/Debian are to be supported eventually, is there a timeline for this? I plan to upgrade some of my personal Systems which where hand built back in the "good" old days, and I would like to give BlueBanquise a shot._

**Comment by oxedions** [comment]
Dear @KeyboardInterrupt 
It should be fixed 😊 
Thanks a lot for your feedback!

_Regarding your question on Ubuntu/Debian support: full Ubuntu 20.04 support should be available with 1.6, so in around 2 month from now. Debian support is expected to be done with 1.7, so more like 4-5 month from now (maybe faster if we solve our current preseed issue with latest Debian)._

**Pull request merged**
